version: "3"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            # - /usr/src/app/node_modules
        env_file:
            - .env
        command: npm run dev
        depends_on:
            - db
    db:
        image: postgres:15
        env_file:
            - .env.db
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
