version: "3"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - .env
        command: npm run dev
        depends_on:
            - db
    db:
        image: postgres:15
        env_file:
            - .env.db
        volumes:
            - postgres:/var/lib/postgresql/data
    # mcu:
    #     build: ./mcu
    #     ports:
    #         - "8888:8888"
    #     volumes:
    #         - ./mcu:/usr/src/mcu
    #     command: npm run start
volumes:
    postgres:
