apiVersion: 1
datasources:
  - name: Prometheus
    uid: vartalaap-prometheus
    type: prometheus
    access: proxy
    url: $PROMETHEUS_URL
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
